FSAEDesigner/urls.py
from django.urls import path
from . import views
from . import views_drf as drf
from django.views.generic.base import TemplateView
from django.conf import settings

app_name = 'FSAEDesigner'
urlpatterns = [
    path('', views.Top.as_view(), name='top'),

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('terms/', TemplateView.as_view(template_name='FSAEDesigner/terms.html'), name="terms"),
    path('user_create/complete/<token>/',
         views.UserCreateComplete, name='user_create_complete'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/confirm/<uidb64>/<token>/',
         views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('email/change/complete/<str:token>/',
         views.EmailChangeComplete, name='email_change_complete'),

    path('api/check_logged_in/', drf.checkLoggedIn, name='check_logged_in'),
    path('api/gd/save_as/', drf.gdSaveAs, name='gd_save_as'),
    path('api/gd/get_all_user_files/', drf.gdGetAllUserFiles, name='gd_get_all_user_files'),
]

if settings.DEBUG:
    urlpatterns.append(path('react/', views.React, name='react')),

project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings

urlpatterns = [
    path('', include('FSAEDesigner.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns = urlpatterns\
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

FSAEDesigner/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import os
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
import secrets
import glob


class CustomUserManager(UserManager):
    # ユーザーマネージャー
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    # ユーザー名（Emailアドレスを使用する）
    email = models.EmailField(_('email address'), unique=True)

    # アバター
    def get_avatar_path(self, filename):
        dir = self.get_public_dir(abs=False)+'avatar/'
        name = self.id
        extension = os.path.splitext(filename)[-1]
        return dir + str(name) + extension
    avatar = ProcessedImageField(upload_to=get_avatar_path,
                                 processors=[ResizeToFill(120, 120)],
                                 format='png',
                                 options={'quality': 100})

    # 通知設定
    push_by_email = models.BooleanField(
        default=False,
        verbose_name=_("Eメールでのpush通知を受け取る"),
    )
    push_by_browser = models.BooleanField(
        default=False,
        verbose_name=_("ブラウザでのpush通知を受け取る"),
    )

    # 非公開オブジェクトの格納フォルダのハッシュ値
    private_dir_hash = models.CharField(
        blank=True, max_length=16,
        verbose_name=_('フォルダ名'),
        help_text=_('フォルダ')
    )

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    # ユーザーの追加日時
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    # カスタムマネージャー
    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def clean(self, *args, **kwargs):
        """
        if self.favorites.count() > 10:
            raise ValidationError(f"登録可能な個数は{MAXFAVORITES}です。")
        """
        super().clean(*args, **kwargs)

    def get_public_dir(self, abs=False):
        root = ""
        if abs:
            root = settings.MEDIA_ROOT.replace(os.sep, '/') + "/"

        dir = f"{root}public/{self.id}/"
        if abs and not os.path.exists(dir):
            os.mkdir(dir)
        return dir

    def get_private_dir(self, abs=False):
        if self.dir_hash == "":
            self.dir_hash = secrets.token_urlsafe(16)
            self.save()
        root = ""
        if abs:
            root = settings.MEDIA_ROOT.replace(os.sep, '/') + "/"

        dir = f"{root}private/{self.dir_hash}/"
        if not os.path.exists(dir):
            os.mkdir(dir)
        return dir

    @ property
    def username(self):
        return self.email

class GeometryDesignerFile(models.Model):
    def get_image_path(self, filename):
        prefix = 'geometry-designer-data/' + str(self.user.id) + "-"
        root = settings.MEDIA_ROOT.replace(os.sep, '/') + "/"
        print(root+prefix)
        folders = glob.glob(root+prefix+"??????????????????????")
        if len(folders) > 0:
            dir_hash = folders[0].split("-")[-1]
            print(dir_hash)
        else:
            dir_hash = secrets.token_urlsafe(16)
        prefix = prefix + dir_hash + "/"
        if not os.path.exists(root+prefix):
            os.mkdir(root + prefix)
        return prefix + filename

        prefix = "robot_log/" + str(self.id)+"-"
        root = settings.MEDIA_ROOT.replace(os.sep, '/') + "/"
        if self.dir_hash == "":
            folders = glob.glob(root+prefix+"????????????????")
            if len(folders) > 0:
                self.dir_hash = folders[0].split("-")[-1]
            else:
                self.dir_hash = secrets.token_urlsafe(16)
            self.save()
        prefix = prefix + self.dir_hash + "/"
        if not os.path.exists(root+prefix):
            os.mkdir(root + prefix)
        return prefix

    name = models.CharField(verbose_name="name",max_length=256)
    note = models.CharField(verbose_name="note",max_length=1024*4,blank=True)

    user = models.ForeignKey(
        User,
        verbose_name=_('user'),
        on_delete=models.CASCADE,
    )

    # 公開するか
    is_public= models.BooleanField(
        _('public'),
        default=False,
    )

    # サムネイル
    thumbnail = ProcessedImageField(upload_to=get_image_path,
                                 processors=[ResizeToFill(512, 512)],
                                 format='png',
                                 blank=True,
                                 options={'quality': 100})
    # JSONの中身(ファイル本体)
    content = models.TextField(verbose_name="content")
    # 作成日時
    created = models.DateTimeField(_('created'), default=timezone.now)
    # 更新日時
    lastUpdated = models.DateTimeField(_('last updated'), default=timezone.now)

    class Meta:
        verbose_name = _('GeometryDesignerFile')
        verbose_name_plural = _('GeometryDesignerFile')

    def clean(self, *args, **kwargs):
        """
        if self.favorites.count() > 10:
            raise ValidationError(f"登録可能な個数は{MAXFAVORITES}です。")
        """
        super().clean(*args, **kwargs)

FSAEDesigner/forms.py
import django.contrib.auth.forms as auth
from django.contrib.auth import get_user_model
User = get_user_model()


class LoginForm(auth.AuthenticationForm):
    # ログインフォーム

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            # placeholderにフィールドのラベルを入れる
            field.widget.attrs['placeholder'] = field.label


class PasswordResetForm(auth.PasswordResetForm):
    # パスワード忘れたときのフォーム
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class SetPasswordForm(auth.SetPasswordForm):
    # パスワード再設定用フォーム(パスワード忘れて再設定)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserCreateForm(auth.UserCreationForm):
    # ユーザー登録用フォーム
    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

    def clean_email(self):
        email = self.cleaned_data['email']
        User.objects.filter(email=email, is_active=False).delete()
        return email

FSAEDesigner/views.py
from django.conf import settings
from django.urls import reverse_lazy
from django.shortcuts import redirect, resolve_url
from django.middleware.csrf import get_token
from django.template.loader import render_to_string
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    LoginView, LogoutView,
    PasswordResetView, PasswordResetConfirmView,
)
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from .forms import (
    LoginForm, PasswordResetForm, SetPasswordForm, UserCreateForm,
)
from django.utils.translation import gettext_lazy as _
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.contrib.auth import get_user_model
User = get_user_model()
"""
このモジュールでは標準的なビューを設定する。
DRFはviews_drf参照のこと
セキュリティのため、認証には標準的なセッションを用いる。
そのため、Topページが呼ばれるまではDjangoの標準的な認証機能を用いる。
認証が成功し、Topが呼ばれた段階でReactとDRFへ引き継ぐ
"""

class CommonMixin():
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["title"] = self.title
        except:
            pass
        return context

class ParentUserTestMixin(UserPassesTestMixin):
    def test_model(self, TestModel):
        user = self.request.user
        try:
            instance = None
            if user.is_superuser:
                instance = TestModel.objects.get(id=self.kwargs['pk'])
            else:
                instance = TestModel.objects.get(
                    user=user, id=self.kwargs['pk'])
            if instance is not None:
                return True
        except:
            return False

class Login(CommonMixin, LoginView):
    # ログインページ
    title = _("ログイン")
    form_class = LoginForm
    template_name = 'FSAEDesigner/login.html'

    def post(self, request, *args, **kwargs):
        if not request.POST.get('remember_me', None):
            request.session.set_expiry(0)
        else:
            request.session.set_expiry(settings.SESSION_COOKIE_AGE)
        return super().post(request, *args, **kwargs)

class Logout(LogoutView):
    # ログアウトページ
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, _("ログアウトしました"))
        return super().dispatch(request, *args, **kwargs)

class PasswordReset(SuccessMessageMixin, PasswordResetView):
    # パスワード変更用URLの送付ページ
    subject_template_name = 'FSAEDesigner/mail_template/password_reset/subject.txt'
    email_template_name = 'FSAEDesigner/mail_template/password_reset/message.txt'
    template_name = 'FSAEDesigner/password_reset_form.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy('FSAEDesigner:password_reset')
    success_message = _("メールを送信しました")

class PasswordResetConfirm(SuccessMessageMixin, PasswordResetConfirmView):
    # 新パスワード入力ページ
    form_class = SetPasswordForm
    template_name = 'FSAEDesigner/password_reset_confirm.html'
    success_url = reverse_lazy('FSAEDesigner:login')
    success_message = _("パスワードが変更されました")

class UserCreate(CommonMixin, SuccessMessageMixin, generic.CreateView):
    title = "新規登録"
    # ユーザー仮登録
    template_name = 'FSAEDesigner/user_create.html'
    success_url = reverse_lazy('FSAEDesigner:user_create')
    success_message = _("登録用メールを送信しました")
    form_class = UserCreateForm

    def form_valid(self, form):
        # 仮登録と本登録用メールの発行.
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string(
            'FSAEDesigner/mail_template/create/subject.txt', context)
        message = render_to_string(
            'FSAEDesigner/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return super().form_valid(form)

def UserCreateComplete(request, token):

    timeout_seconds = getattr(
        settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  #1日以内

    # tokenが正しければ本登録.
    try:
        user_pk = loads(token, max_age=timeout_seconds)

    # 期限切れ
    except SignatureExpired:
        return HttpResponseBadRequest()

    # tokenが間違っている
    except BadSignature:
        return HttpResponseBadRequest()

    # tokenは問題なし
    else:
        try:
            user = User.objects.get(pk=user_pk)
        except User.DoesNotExist:
            return HttpResponseBadRequest()
        else:
            if not user.is_active:
                # 問題なければ本登録とする
                user.is_active = True
                user.save()
                messages.success(request, _("登録が完了しました"))
                #ログイン画面へリダイレクト
                return redirect('FSAEDesigner:login')

        return HttpResponseBadRequest()

@login_required
def EmailChangeComplete(request, token):
    """メールアドレスが変更されたらログインページへリダイレクトする"""
    timeout_seconds = getattr(
        settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*1)  # デフォルトでは1日以内

    try:
        new_email = loads(token, max_age=timeout_seconds)

    # 期限切れ
    except SignatureExpired:
        return HttpResponseBadRequest()

    # tokenが間違っている
    except BadSignature:
        return HttpResponseBadRequest()

    # tokenは問題なし
    else:
        User.objects.filter(email=new_email, is_active=False).delete()
        request.user.email = new_email
        request.user.save()
        messages.success(request, _("メールアドレスが変更されました"))
        return redirect('FSAEDesigner:login')

class Top(CommonMixin, LoginRequiredMixin, generic.TemplateView):
    title = _("")
    template_name = 'FSAEDesigner/top.html'
    """
    def get(self, request, *args, **kwargs):
        self.url = reverse_lazy('FSAEDesigner:top')
        return super().get(request, *args, **kwargs)
    """


@login_required
def React(request):
    session_key = request.session.session_key
    #token = get_token(request)
    token = request.META["CSRF_COOKIE"]
    return redirect(f'http://127.0.0.1:3000?session_key={session_key}&'\
        f'csrf_token={token}')

FSAEDesigner/templates/FSAEDesigner/base.html
{% load adminlte_helpers i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
    <title>{% block title %}{{title}}{% endblock %} | FSAEDesigner</title>
    {% endblock %}
    {% block meta %}
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
    {% include 'FSAEDesigner/lib/_auth_styles.html' %}
    {% endblock %}
    {% block extra_head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini {% block body_class %}{% block bodyclass %}{% endblock %}{% endblock %}">
    {% csrf_token %}
    {% block body %}
    {% endblock body %}

    {% block javascript %}
    {% include 'FSAEDesigner/lib/_auth_scripts.html' %}
    {% endblock %}
    {% block extra_js %}
    {% endblock %}
</body>
</html>

FSAEDesigner/templates/FSAEDesigner/login.html
{% extends "FSAEDesigner/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block extra_stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'FSAEDesigner/css/custom.css' %}">
{% endblock %}


{% block body %}
<div class="login-box">
    {% block logo %}
    <div class="login-logo">
        {# Mirrors block names used in _main_header.html #}
        <a href="{% block logo_href %}{% url 'FSAEDesigner:top' %}{% endblock %}">{% block logo_text %}FSAEDesigner{% endblock %}</a>
    </div>
    {% endblock %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible">
        <h5><i class="icon fas fa-check"></i> </h5>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-body login-card-body">
            {% block login_errors %}
            {% if form.errors and not form.non_field_errors %}
            <p class="alert alert-danger">
                {% trans "以下のエラーを修正してください" %}
            </p>
            {% endif %}

            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class="alert alert-danger">
                {{ error }}
            </p>
            {% endfor %}
            {% endif %}
            {% endblock login_errors %}
            {% block login_form %}
            <form action="{% url 'FSAEDesigner:login' %}" method="post">
                {% csrf_token %}
                {% if message %}
                <p class="login-box-msg" style="color: red;">{{ message }}</p>
                {% endif %}
                <div class="input-group mb-3">
                    {{ form.username }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                    {{ form.username.errors }}
                </div>
                <div class="input-group mb-3">
                    {{ form.password }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                    {{ form.password.errors }}
                </div>
                <div class="row">
                    <div class="col-7">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember" name="remember_me">
                            <label for="remember">
                                {% trans "保存する" %}
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-5">
                        <button type="submit" class="btn btn-primary btn-block text-nowrap ">{% trans "サインイン" %}</button>
                    </div>
                    <!-- /.col -->
                </div>
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
            {% endblock login_form %}
            <p class="mb-1">
                <a href="{% url 'FSAEDesigner:password_reset' %}">{% trans "パスワードを忘れた場合" %}</a>
            </p>
            <p class="mb-0">
                <a href="{% url 'FSAEDesigner:user_create' %}" class="text-center">{% trans "新規登録" %}</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
{% endblock %}

FSAEDesigner/templates/FSAEDesigner/password_reset_confirm.html
{% extends "FSAEDesigner/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block body %}
<div class="login-box">
    {% block logo %}
    <div class="login-logo">
        {# Mirrors block names used in _main_header.html #}
        <a href="{% block logo_href %}{% url 'FSAEDesigner:top' %}{% endblock %}">{% block logo_text %}FSAEDesigner{% endblock %}</a>
    </div>
    {% endblock %}
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">
                {% trans "パスワードの再設定を行ってください" %}
            </p>
            {% block login_errors %}
            {% if form.errors and not form.non_field_errors %}
            <p class="alert alert-danger">
                {% trans "以下のエラーを修正してください" %}
            </p>
            {% endif %}
            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class="alert alert-danger">
                {{ error }}
            </p>
            {% endfor %}
            {% endif %}
            {% endblock login_errors %}

            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-group mb-3">
                    {{ field }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">
                            {% trans "パスワードを再設定" %}
                        </button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="{% url 'FSAEDesigner:login' %}">
                    {% trans "サインイン" %}
                </a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
{% endblock %}

FSAEDesigner/templates/FSAEDesigner/password_reset_form.html
{% extends "FSAEDesigner/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block body %}
<div class="login-box">
    {% block logo %}
    <div class="login-logo">
        {# Mirrors block names used in _main_header.html #}
        <a href="{% block logo_href %}{% url 'FSAEDesigner:top' %}{% endblock %}">{% block logo_text %}FSAEDesigner{% endblock %}</a>
    </div>
    {% endblock %}
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">
                {% trans "メールアドレスを入力してください。再設定用のリンクが送信されます。" %}
            </p>
            {% block login_errors %}
            {% if form.errors and not form.non_field_errors %}
            {% trans "以下のエラーを修正してください" %}
            {% endif %}

            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class="alert alert-danger">
                {{ error }}
            </p>
            {% endfor %}
            {% endif %}
            {% endblock login_errors %}

            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-group mb-3">
                    {{ field }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">
                            {% trans "パスワード再設定用URLを送信" %}
                        </button>
                        {% if messages %}
                        {% for message in messages %}
                        <li>
                            {{ message }}
                        </li>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="{% url 'FSAEDesigner:login' %}">
                    {% trans "サインイン" %}
                </a>
            </p>
            <p class="mb-0">
                <a href="{% url 'FSAEDesigner:user_create' %}" class="text-center">
                    {% trans "新規登録" %}
                </a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
{% endblock %}

FSAEDesigner/templates/FSAEDesigner/user_create.html
{% extends "FSAEDesigner/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block body %}
<div class="register-box">
    {% block logo %}
    <div class="login-logo">
        {# Mirrors block names used in _main_header.html #}
        <a href="{% block logo_href %}{% url 'FSAEDesigner:top' %}{% endblock %}">{% block logo_text %}FSAE Designer{% endblock %}</a>
    </div>
    {% endblock %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible">
        <h5><i class="icon fas fa-check"></i> </h5>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">新規登録フォーム</p>
            {% block login_errors %}
            {% if form.errors and not form.non_field_errors %}
            <p class="alert alert-danger">
                            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                                {% trans "Please correct the errors below." %}{% endif %}
                        </p>
            {% endif %}

            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class="alert alert-danger">
                {{ error }}
            </p>
            {% endfor %}
            {% endif %}
            {% endblock login_errors %}

            <form action="" method="post">
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="input-group mb-3">
                    {{ field }}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            {% if field.name == "email" %}
                            <span class="fas fa-envelope"></span>
                            {% else %}
                            <span class="fas fa-lock"></span>
                            {% endif %}
                        </div>
                    </div>
                    {{ field.errors }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="agreeTerms" name="terms" value="agree">
                            <label for="agreeTerms">
                                <a href="{% url 'FSAEDesigner:terms' %}" target="_blank" rel="noopener noreferrer">利用規約</a>に同意します
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" id="register" class="btn btn-primary btn-block" disabled="disabled">新規作成</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>
            <a href="{% url 'FSAEDesigner:login' %}" class="text-center">すでにアカウントをお持ちですか？</a>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    $(function () {
        $('#register').attr('disabled', 'disabled'); //①
        $('#agreeTerms').click(function () { //②
            if ($(this).prop('checked') == false) {　//③
                $('#register').attr('disabled', 'disabled');　//④
            } else {
                $('#register').removeAttr('disabled');　//⑤
            }
        });
    });
</script>
{% endblock %}